name: Release

on:
  push:
  release:
    branches: [main]
    types:
      - published
    paths-ignore:
      - "**.md"
      - "**.spec.js"
      - ".idea"
      - ".vscode"
      - ".dockerignore"
      - "Dockerfile"
      - ".gitignore"
      - ".github/**"
      - "!.github/workflows/release.yml"

defaults:
  run:
    shell: "bash"

jobs:
  build:
    runs-on: ${{ matrix.os }}

    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      VITE_NFT_STORAGE_TOKEN: ${{ secrets.NFT_STORAGE_TOKEN }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node: ["18"]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1


      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: yarn install

      # - name: Run tests
      #   run: npm run test

      # - name: Build dependencies
      #   run: npm run build
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - uses: actions/upload-artifact@v2
      #   with:
      #     name: upload-artifact
      #     path: |
      #       release/mintgarden-studio*.exe
      #       release/mintgarden-studio*.AppImage
      #       release/mintgarden-studio*.snap

      # https://github.com/marketplace/actions/electron-builder-action
      - name: Compile & Release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          args: --config electron-builder.json5
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release: ${{ startsWith(github.ref, 'refs/tags/v') && github.event_name == 'push' && needs.get_metadata.outputs.branch == 'main'}}
          mac_certs: ${{ secrets.MAC_CERTS }}
          mac_certs_password: ${{ secrets.MAC_CERTS_PASSWORD }}
